dist: xenial
language: python
python:
- '3.7'
install: pip install tox
script: tox
notifications:
  email: false
  slack:
    secure: gcF1BybNKCVDCPg9h59lsueCFAttC/sV1pg7ehiLLzsJcdFkVqY+3X3KBxmGmbQwfGYLRVL6B/rmwc6tmYHC5MaVgTwptK5D8oNLTIYZZa+s9HiFFJhn/4rigwlxL99VzKIh9RQXXNurpCLKCAxGdmQ12HeeroDOK0R08IxjP17TiZc8WCswCL3WoUgEXG/+lUheuBfIwn/61aR6vhqRsF4mDJMhetE9ZqRWicNQEDXjCaj8HeVicpbQdqWQHhHzOvyk9j1qkMPUq+f0rlqDU9mdOqc9WaNWxtMq7K2Q4L+n3du3npmgeg96scp0syvI8W7A0+p+t3plDBecIEA3IX50NAZUxF+B6h5jpYA0RkyeAAKCBGv7BFL8Uut3mlpkS6mR3zJnEwJ0PXP6EAK7g/xmI2KULlvMvZjb+YYMeA5u9+OHCoBgVTnD/e3xt54f1ykyyRayap2W7adoDj/Tlj3NyYXMDDH4P66WIgfB7OYvTtYTbwqrWDCdFUXAf7H+S2pPXd0T241ZEDbmfG2mIx6npdJEAhHm8GL4B6qgjSroQO41fYREeWiXYtB4IHG576JatIpELidG12WYX48i63jyuik8So8r16h3MQ3+k7S7U9g0KxSBVPA4mapLNsCsAOB5GqmCcp2EVOF7GD8pwR/ICoc6EVnGJT1F9mjW2uI=
deploy:
  provider: pypi
  user: jalanb
  on:
    tags: true
  password:
    secure: g/XxaPnc2BgNWDy66OLyJ4lavMNUqmy8uwJzqBy52LZQ8+tRk+GMUo5fncIBju/Gr1vNechrx1dfEyAEFQo80dlFhSIVm2UHn/2bV2j7iMH/y3timoNnFbIW9S3M54vHRhwg2G3JgU3Stzy5B/Rbxk8sruFb6juf08T5xXTfH3A=
